name = "mark-project-v1"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "prod-app-db-v1"
database_id = "e4df61d5-ae36-414f-adeb-a501e1e382ed"
